version: "3.2"
services:
  db:
    image: groonga/mroonga:mysql-8.4.8-15.25
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: imas_cg
      MYSQL_PASSWORD: imas_cg
      MYSQL_DATABASE: imas_cg
    volumes:
      - type: bind
        source: ./sql
        target: /docker-entrypoint-initdb.d
  app:
    build: .
    command: python /home/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      DJANGO_SETTINGS_MODULE : "api.settings.docker"
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./
        target: /home
