[project]
name = "suteki_blog_api"
version = "0.1.0"
description = "THE IDOLM@STER CINDERELLA GIRLS IDOL DATA API"
requires-python = ">=3.8"
dependencies = [
    "django>=3.2,<5",
    "djangorestframework>=3.11,<4",
    "django-cors-headers>=3.2,<4",
    "mysqlclient>=2.0,<3",
]
